version: 1.0.{build}

image: Visual Studio 2017

configuration:
  - Release

before_build:
  dotnet restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

artifacts:
  - path: '**\*.nupkg'

test_script: 
  cmd: >-
    dotnet test AsyncEnumerable.UnitTests\AsyncEnumerable.UnitTests.csproj

after_test:
  - dotnet pack --no-build

deploy:
  provider: NuGet
  api_key:
    secure: er/U2/CvQ1PB7fzqLd58D6wEGLFo7jaOu1Id6ruQ8OeMckIgwqSXBtIz0rbIs3pQ
  artifact: '**\.*.nupkg'